### ISSUE TITLE
Love to see an Ultra Low Power ESP32 S2/S3 example - Long Term Aim

### ISSUE THREAD

**Issue by tyeth** [Sensirion/embedded-i2c-sen5x#1]
Hi, the Espressif ESP32 S2/S3 chips support an Ultra Low Power processor with RISC (or an older Finite State Machine like ESP32 v1 but ignore that). 
Would this be compatible with the SEN55, or only possible to read measurements when out of sleep mode to support multi-byte data registers/communications? (See comment here https://github.com/tomtor/ulp-i2c#i2c-bit-banged-support )
 I am also likely getting the wrong end of the stick as my knowledge of the ULP architecture is newly acquired. I assume (wrongly?) that the bitbang gpio version could be made to work, but ideally the i2c instructions could be a lot more efficient. There's a bitbang example for the DS18b20 temp sensor 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/ulp-risc-v.html#application-examples
 I think the ESP-IDF is sticking at v4.4 (branch release/v4.4) for a while (in arduino and platformIO) which doesn't include the i2c ULP example listed here: 
https://github.com/espressif/esp-idf/tree/439a709c4298b0f613d09b47fc0b7b9728fc5733/examples/system/ulp_riscv/i2c

**Comment by psachs** [comment]
For communication I recommend using I2C if available. Bit banging is a alternative that can be used if no regular I2C functionality is available.
For ultra low power
The SEN55 is a module that is intended to be always on and run measurements once per second check-out the SEN5x datasheet if this meets your requirement.
https://sensirion.com/media/documents/6791EFA0/62A1F68F/Sensirion_Datasheet_Environmental_Node_SEN5x.pdf

As long as the SEN55 is powered and and measurement is started it will internally measure every 1 second. You can than read out the current values whenever your processor is ready to do so.
For your processor to communicate with the module it has to be out of sleep mode, else you need some co-processor for the measurement routine.

**Comment by tyeth** [comment]
Hi, thanks for the reply. I hadn't truly appreciated that it was meant specifically for a 1second sample in continuous monitoring. I now understand that it appears that the default mode is setup for air conditioning situation rather than air quality sampling which has lower duty cycle requirements. It reads in the docs like I can use this still for Air Quality Sensor in low power scenario as long as I adjust the PM duty versus RHT/VOC duty versus idle/off time, also setting the appropriate parameters/modes.

Having gone through the application notes it seems acceptable to go with a 5minute high power cycle, with 30seconds warming then 30seconds sampling, and then switch the device off for 4minutes, then restore from previous data (recommended power-on data valid for ten minutes, to be updated every 2hrs) on wake and 30s stabilise then 30s sample again. I am not especially interested in the temp/humidity over the low power period so off is probably better than RHT mode, but I would probably have a flag to choose RHT or Off/Idle mode to save extra milli-amps.

So what I'm dreaming of is using this for Air Quality Sensor rather than having 3 separate devices, and attempting to run from battery, and sudden temperature/voc events are not important/expected but should be picked up at a 5minute sample rate. I think personally I'm not capable yet of doing the i2c in ULP mode, but will come back and update this once I get there...

**Comment by psachs** [comment]
Hi @tyeth 

Thanks for clarification. Of course you can use the SEN55 in different modes that fits your requirements. If you are not interested in real time events and are willing to sacrifice some performance for a ULP mode this module can fit your requirement.
Let us know if we can help you with your use case and of course I am happy to hear about your progress.
